spring:
  application:
    name: ProductsService
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/products_service
    username: products_service
    password: products_service
  messages:
    basename: i18n/messages
  thymeleaf:
    enabled: true
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: true
  task:
    execution:
      thread-name-prefix: products-service-task-
      pool:
        core-size: 2
        max-size: 50
        queue-capacity: 10000
    scheduling:
      thread-name-prefix: products-service-scheduling-
      pool:
        size: 2
  flyway:
    locations: classpath:db/migration/common,classpath:db/migration/dev
    placeholders:
      currencies:
        pln:
          name: Polish Złoty
          symbol: PLN
        euro:
          name: Euro
          symbol: €
        dollar:
          name: US Dollar
          symbol: $
      shops:
        lidl: Lidl
        intermarche: Intermarché
        carrefour: Carrefour
        auchan: Auchan
        netto: Netto
        aldi: Aldi
        kaufland: Kaufland
        ikea: Ikea


logging:
  level:
    ROOT: INFO
    tech.przybysz.pms.filemanager: DEBUG

server:
  port: 8084
